services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: healthlink-postgres
    environment:
      - 'POSTGRES_DB=healthlink'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d healthlink" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
