services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: healthlink-postgres
    environment:
      - 'POSTGRES_DB=healthlink'
      - 'POSTGRES_PASSWORD=healthlink123'
      - 'POSTGRES_USER=healthlink_user'
    ports:
      - '5433:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U healthlink_user -d healthlink" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
